# Generated by Django 4.1.7 on 2023-06-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotutorial',
            name='video_url',
        ),
    ]
