# Generated by Django 4.1.7 on 2023-06-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_videotutorial_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotutorial',
            old_name='service',
            new_name='services',
        ),
    ]
