# Generated by Django 4.1.7 on 2023-06-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_service_videotutorial_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotutorial',
            old_name='services',
            new_name='service',
        ),
    ]
